version: "3"

services:
  database:
    image: neo4j:latest
    ports:
      - "7687:7687"
      - "7474:7474"
    environment:
      NEO4J_AUTH: none
    volumes:
      - ./data:/data
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "4000:4000"
    depends_on:
      - database
    networks:
      - app-network
    env_file:
      - ./backend/.env
    command: sh -c "sleep 30 && node app.js"

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network
    env_file:
      - ./frontend/.env

networks:
  app-network:
    driver: bridge
