name: ESLint & Tests - Backend

on:
  push:
    branches:
      - '*'
    paths:
      - 'backend/**'
jobs:
  backend-eslint-and-tests:
    runs-on: ubuntu-latest
    env:
      ISSUER_BASE_URL: ${{ secrets.ISSUER_BASE_URL }}
      AUDIENCE: ${{ secrets.AUDIENCE }}
      SECRET: ${{ secrets.SECRET }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install
        working-directory: ./backend

      - name: Run ESLint
        run: yarn lint
        working-directory: ./backend

      - name: Run tests
        run: yarn test
        working-directory: ./backend
